from . import realty_permission_tracker
from . import realty_policy
from . import realty_Real_Estate_status
from . import realty_Real_Estate_type
from . import realty_tag
from . import realty_Real_Estate_feature
from . import realty_Real_Estate_reason
from . import realty_Real_Estate_group_home_direction
from . import realty_Real_Estate_home_direction
from . import realty_Real_Estate_land_title
from . import realty_Real_Estate_unit_price
from . import realty_region
from . import VNadmin_province
from . import VNadmin_district
from . import VNadmin_commune
from . import res_users
from . import res_partner
from . import realty_create_user_wizard
from . import realty_assign_employee_wizard
from . import hr_job
from . import hr_job_wizard
from . import hr_department
from . import hr_employee
from . import hr_employee_wizard
from . import res_company
from . import ir_filters
from . import product_template
from . import mail_tracking_value
from . import realty_Report_client_feedback
from . import realty_Report_owner_feedback
from . import realty_Real_Estate_report
from . import realty_notify
from . import realty_Notify_moderator_assignment_sequence
from . import realty_Notify_guideline
from . import realty_Notify_urgent_buying
from . import realty_Notify_congratulation
from . import realty_Notify_notification
from . import realty_Notify_moderator_guideline
from . import realty_Notify_reject_reason
from . import realty_Notify_remove_reason
from . import realty_Notify_wizard
from . import realty_comment_wizard
from . import realty_Notify_comment
from . import ir_attachment
from . import realty_product_wizard
from . import realty_user_evaluation
from . import realty_user_evaluation_wizard