from . import realty_Real_Estate_status
from . import realty_Real_Estate_type
from . import realty_tag
from . import realty_policy
from . import realty_Real_Estate_feature
from . import realty_Real_Estate_reason
from . import realty_Real_Estate_group_home_direction
from . import realty_Real_Estate_home_direction
from . import realty_Real_Estate_land_tittle
from . import realty_Real_Estate_unit_price
from . import realty_region
from . import VNadmin_province
from . import VNadmin_district
from . import VNadmin_commune
from . import res_users
from . import res_partner
from . import realty_create_user_wizard
from . import realty_assign_employee_wizard
from . import hr_job
from . import hr_department
from . import hr_employee
from . import res_company
from . import ir_filters
from . import product_template
from . import mail_tracking_value
from . import realty_Report_client_feedback
from . import realty_Report_owner_feedback
from . import realty_Real_Estate_report